export const BlogsData = [
    {
        id:'1',
        snippet: "HOMEPAGE FEATURED",
        title: "6 Green Leaves You Should try in your daily Diet",
        img: "https://media.istockphoto.com/photos/people-having-balanced-diet-from-lunch-boxes-picture-id1321195603?b=1&k=20&m=1321195603&s=170667a&w=0&h=oJkXy1GKpHnCCzcYIpjue_luwxLlnoFj2zU1MMn5aNM=",
        content: ` Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero dolore reprehenderit velit beatae minima consequuntur laborum ratione quos vel. Autem deleniti animi accusamus maiores iure amet obcaecati voluptas beatae impedit?
        Animi numquam, illum minus quis beatae eveniet facere reiciendis ipsum natus vero recusandae temporibus nisi consequuntur error facilis et necessitatibus similique dolorem accusamus dolorum officia veritatis! Dignissimos cum nesciunt aperiam!
        Cum, repellendus aut, accusantium veniam iste eligendi quod est voluptate atque voluptatem culpa et adipisci ullam eos fugit nobis officiis voluptates! Ut voluptates architecto nulla maiores voluptatibus rerum explicabo! Ex?
        Ipsum culpa ullam unde laborum voluptatum harum hic natus consectetur aut vel tempore repudiandae doloremque, necessitatibus numquam facilis animi, nulla, consequuntur explicabo. Dicta error repellendus nostrum magni molestias possimus dignissimos?
        Non, quod esse. Alias necessitatibus obcaecati suscipit cum cupiditate praesentium rem, accusamus asperiores amet quam modi molestias reprehenderit recusandae accusantium earum odio animi voluptatibus, nisi itaque totam repellendus delectus molestiae!
        Corporis, minima ab tempore illum voluptates similique mollitia voluptatibus recusandae est nemo ad quo iste doloremque esse a quasi, aperiam consequuntur ut tenetur omnis? Libero, voluptas sed. Sunt, sint eligendi?
        Numquam nulla veritatis deleniti eum sunt aliquam quam non asperiores laboriosam officia impedit ad aperiam inventore reiciendis alias, eveniet voluptatem quis adipisci soluta molestias? Culpa ex distinctio debitis laudantium quo.
        Optio, repellat error. Quod ducimus adipisci, ex molestias soluta sit reprehenderit, consequuntur hic doloremque eveniet, pariatur quisquam dolorum. Officiis illo quia eaque eligendi odio suscipit cumque veniam doloribus id a.
        Minima, beatae corporis nesciunt quos sequi quidem quo! Exercitationem ab, et, eius ullam itaque modi, atque dolor aliquam obcaecati tenetur alias rerum aliquid repudiandae! Sunt voluptatibus quas animi laboriosam mollitia!
        Molestiae earum reiciendis dicta perferendis tempora qui, impedit voluptates eius velit laboriosam rerum architecto itaque, consequuntur eligendi officia? Dolor, dolorem! Commodi asperiores illum a harum quisquam laborum alias sed deserunt.
        Ducimus, hic autem. Repudiandae reiciendis quidem similique numquam modi temporibus dolore nihil fugit minus placeat soluta, cum quaerat. Quam obcaecati nihil aliquam repellendus repudiandae reiciendis quia dolorem quis dolorum error.
        Dolorum blanditiis unde voluptatem corporis pariatur necessitatibus fuga praesentium ducimus ab neque provident consequuntur voluptate vitae exercitationem voluptatum aliquid ullam consectetur laboriosam nesciunt, earum ipsum laudantium at veniam? Provident, laudantium?
        Labore mollitia omnis saepe doloribus excepturi culpa repudiandae aliquam, quos eligendi reiciendis similique, minima a ea incidunt, quod ipsum aspernatur facere debitis. Fugit repellat libero beatae non suscipit officia neque.
        Saepe, sequi ipsam fuga nemo facilis aliquid earum laborum voluptas dolorem laboriosam. Recusandae maxime omnis placeat earum ipsam nostrum architecto debitis minus unde, eveniet quae, est illo eligendi quod dolore.
        Cupiditate minus tempora, dolor ea nisi iste veniam odio obcaecati adipisci ut quas reprehenderit qui nemo repellat beatae praesentium! Architecto harum eum, voluptates perspiciatis dignissimos laborum a beatae optio reiciendis.
        Fugit id molestiae incidunt voluptatibus quaerat cum non dolorum necessitatibus magni soluta velit veniam quas nam labore possimus excepturi obcaecati et perspiciatis laboriosam voluptates laudantium, pariatur, expedita nobis. At, pariatur?
        Numquam officiis, perferendis temporibus voluptatum totam enim porro dignissimos dolore? Minus explicabo earum amet consequuntur id voluptatibus quisquam quaerat a beatae, cumque harum illum debitis neque rem rerum nisi aliquid.
        Vitae itaque dolores, reiciendis ut quos porro modi. Illum voluptas voluptates accusamus nam neque earum doloribus, possimus officiis excepturi id! Neque necessitatibus sunt illo molestiae at reprehenderit distinctio quasi unde?
        Repellendus, quidem non! Omnis corporis, reprehenderit dicta, dolorem quam nulla deserunt tenetur, nisi voluptatum aperiam vero numquam ipsam! Veniam assumenda eligendi iure tempore, quis veritatis dolorum optio corrupti maiores provident?
        Sunt hic quis porro iure voluptatem molestias quod velit tenetur, voluptates unde veniam officia alias accusantium inventore asperiores commodi sed ex dolores vel corporis maiores numquam! Totam cum beatae quo.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero dolore reprehenderit velit beatae minima consequuntur laborum ratione quos vel. Autem deleniti animi accusamus maiores iure amet obcaecati voluptas beatae impedit?`
    },
    {
        id:'2',
        snippet: "FOOD",
        title: "Low your Blood Suger with these Healthy Vegetables",
        img: "https://media.istockphoto.com/photos/healthy-buddha-bowl-lunch-with-grilled-chicken-quinoa-spinach-avocado-picture-id920931456?k=20&m=920931456&s=612x612&w=0&h=s-X-_8QT27E62QYufCKClGhCEiv687MXuXcbVQnRi5E=",
        content: ` Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero dolore reprehenderit velit beatae minima consequuntur laborum ratione quos vel. Autem deleniti animi accusamus maiores iure amet obcaecati voluptas beatae impedit?
        Animi numquam, illum minus quis beatae eveniet facere reiciendis ipsum natus vero recusandae temporibus nisi consequuntur error facilis et necessitatibus similique dolorem accusamus dolorum officia veritatis! Dignissimos cum nesciunt aperiam!
        Cum, repellendus aut, accusantium veniam iste eligendi quod est voluptate atque voluptatem culpa et adipisci ullam eos fugit nobis officiis voluptates! Ut voluptates architecto nulla maiores voluptatibus rerum explicabo! Ex?
        Ipsum culpa ullam unde laborum voluptatum harum hic natus consectetur aut vel tempore repudiandae doloremque, necessitatibus numquam facilis animi, nulla, consequuntur explicabo. Dicta error repellendus nostrum magni molestias possimus dignissimos?
        Non, quod esse. Alias necessitatibus obcaecati suscipit cum cupiditate praesentium rem, accusamus asperiores amet quam modi molestias reprehenderit recusandae accusantium earum odio animi voluptatibus, nisi itaque totam repellendus delectus molestiae!
        Corporis, minima ab tempore illum voluptates similique mollitia voluptatibus recusandae est nemo ad quo iste doloremque esse a quasi, aperiam consequuntur ut tenetur omnis? Libero, voluptas sed. Sunt, sint eligendi?
        Numquam nulla veritatis deleniti eum sunt aliquam quam non asperiores laboriosam officia impedit ad aperiam inventore reiciendis alias, eveniet voluptatem quis adipisci soluta molestias? Culpa ex distinctio debitis laudantium quo.
        Optio, repellat error. Quod ducimus adipisci, ex molestias soluta sit reprehenderit, consequuntur hic doloremque eveniet, pariatur quisquam dolorum. Officiis illo quia eaque eligendi odio suscipit cumque veniam doloribus id a.
        Minima, beatae corporis nesciunt quos sequi quidem quo! Exercitationem ab, et, eius ullam itaque modi, atque dolor aliquam obcaecati tenetur alias rerum aliquid repudiandae! Sunt voluptatibus quas animi laboriosam mollitia!
        Molestiae earum reiciendis dicta perferendis tempora qui, impedit voluptates eius velit laboriosam rerum architecto itaque, consequuntur eligendi officia? Dolor, dolorem! Commodi asperiores illum a harum quisquam laborum alias sed deserunt.
        Ducimus, hic autem. Repudiandae reiciendis quidem similique numquam modi temporibus dolore nihil fugit minus placeat soluta, cum quaerat. Quam obcaecati nihil aliquam repellendus repudiandae reiciendis quia dolorem quis dolorum error.
        Dolorum blanditiis unde voluptatem corporis pariatur necessitatibus fuga praesentium ducimus ab neque provident consequuntur voluptate vitae exercitationem voluptatum aliquid ullam consectetur laboriosam nesciunt, earum ipsum laudantium at veniam? Provident, laudantium?
        Labore mollitia omnis saepe doloribus excepturi culpa repudiandae aliquam, quos eligendi reiciendis similique, minima a ea incidunt, quod ipsum aspernatur facere debitis. Fugit repellat libero beatae non suscipit officia neque.
        Saepe, sequi ipsam fuga nemo facilis aliquid earum laborum voluptas dolorem laboriosam. Recusandae maxime omnis placeat earum ipsam nostrum architecto debitis minus unde, eveniet quae, est illo eligendi quod dolore.
        Cupiditate minus tempora, dolor ea nisi iste veniam odio obcaecati adipisci ut quas reprehenderit qui nemo repellat beatae praesentium! Architecto harum eum, voluptates perspiciatis dignissimos laborum a beatae optio reiciendis.
        Fugit id molestiae incidunt voluptatibus quaerat cum non dolorum necessitatibus magni soluta velit veniam quas nam labore possimus excepturi obcaecati et perspiciatis laboriosam voluptates laudantium, pariatur, expedita nobis. At, pariatur?
        Numquam officiis, perferendis temporibus voluptatum totam enim porro dignissimos dolore? Minus explicabo earum amet consequuntur id voluptatibus quisquam quaerat a beatae, cumque harum illum debitis neque rem rerum nisi aliquid.
        Vitae itaque dolores, reiciendis ut quos porro modi. Illum voluptas voluptates accusamus nam neque earum doloribus, possimus officiis excepturi id! Neque necessitatibus sunt illo molestiae at reprehenderit distinctio quasi unde?
        Repellendus, quidem non! Omnis corporis, reprehenderit dicta, dolorem quam nulla deserunt tenetur, nisi voluptatum aperiam vero numquam ipsam! Veniam assumenda eligendi iure tempore, quis veritatis dolorum optio corrupti maiores provident?
        Sunt hic quis porro iure voluptatem molestias quod velit tenetur, voluptates unde veniam officia alias accusantium inventore asperiores commodi sed ex dolores vel corporis maiores numquam! Totam cum beatae quo.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero dolore reprehenderit velit beatae minima consequuntur laborum ratione quos vel. Autem deleniti animi accusamus maiores iure amet obcaecati voluptas beatae impedit?`
    },
    {
        id:'3',
        snippet: "Healh",
        title: "Low your Blood Suger with these Healthy Vegetables",
        img: "https://images.unsplash.com/photo-1514986888952-8cd320577b68?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8a2l0Y2hlbiUyMGZvb2R8ZW58MHx8MHx8&w=1000&q=80",
        content: ` Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero dolore reprehenderit velit beatae minima consequuntur laborum ratione quos vel. Autem deleniti animi accusamus maiores iure amet obcaecati voluptas beatae impedit?
        Animi numquam, illum minus quis beatae eveniet facere reiciendis ipsum natus vero recusandae temporibus nisi consequuntur error facilis et necessitatibus similique dolorem accusamus dolorum officia veritatis! Dignissimos cum nesciunt aperiam!
        Cum, repellendus aut, accusantium veniam iste eligendi quod est voluptate atque voluptatem culpa et adipisci ullam eos fugit nobis officiis voluptates! Ut voluptates architecto nulla maiores voluptatibus rerum explicabo! Ex?
        Ipsum culpa ullam unde laborum voluptatum harum hic natus consectetur aut vel tempore repudiandae doloremque, necessitatibus numquam facilis animi, nulla, consequuntur explicabo. Dicta error repellendus nostrum magni molestias possimus dignissimos?
        Non, quod esse. Alias necessitatibus obcaecati suscipit cum cupiditate praesentium rem, accusamus asperiores amet quam modi molestias reprehenderit recusandae accusantium earum odio animi voluptatibus, nisi itaque totam repellendus delectus molestiae!
        Corporis, minima ab tempore illum voluptates similique mollitia voluptatibus recusandae est nemo ad quo iste doloremque esse a quasi, aperiam consequuntur ut tenetur omnis? Libero, voluptas sed. Sunt, sint eligendi?
        Numquam nulla veritatis deleniti eum sunt aliquam quam non asperiores laboriosam officia impedit ad aperiam inventore reiciendis alias, eveniet voluptatem quis adipisci soluta molestias? Culpa ex distinctio debitis laudantium quo.
        Optio, repellat error. Quod ducimus adipisci, ex molestias soluta sit reprehenderit, consequuntur hic doloremque eveniet, pariatur quisquam dolorum. Officiis illo quia eaque eligendi odio suscipit cumque veniam doloribus id a.
        Minima, beatae corporis nesciunt quos sequi quidem quo! Exercitationem ab, et, eius ullam itaque modi, atque dolor aliquam obcaecati tenetur alias rerum aliquid repudiandae! Sunt voluptatibus quas animi laboriosam mollitia!
        Molestiae earum reiciendis dicta perferendis tempora qui, impedit voluptates eius velit laboriosam rerum architecto itaque, consequuntur eligendi officia? Dolor, dolorem! Commodi asperiores illum a harum quisquam laborum alias sed deserunt.
        Ducimus, hic autem. Repudiandae reiciendis quidem similique numquam modi temporibus dolore nihil fugit minus placeat soluta, cum quaerat. Quam obcaecati nihil aliquam repellendus repudiandae reiciendis quia dolorem quis dolorum error.
        Dolorum blanditiis unde voluptatem corporis pariatur necessitatibus fuga praesentium ducimus ab neque provident consequuntur voluptate vitae exercitationem voluptatum aliquid ullam consectetur laboriosam nesciunt, earum ipsum laudantium at veniam? Provident, laudantium?
        Labore mollitia omnis saepe doloribus excepturi culpa repudiandae aliquam, quos eligendi reiciendis similique, minima a ea incidunt, quod ipsum aspernatur facere debitis. Fugit repellat libero beatae non suscipit officia neque.
        Saepe, sequi ipsam fuga nemo facilis aliquid earum laborum voluptas dolorem laboriosam. Recusandae maxime omnis placeat earum ipsam nostrum architecto debitis minus unde, eveniet quae, est illo eligendi quod dolore.
        Cupiditate minus tempora, dolor ea nisi iste veniam odio obcaecati adipisci ut quas reprehenderit qui nemo repellat beatae praesentium! Architecto harum eum, voluptates perspiciatis dignissimos laborum a beatae optio reiciendis.
        Fugit id molestiae incidunt voluptatibus quaerat cum non dolorum necessitatibus magni soluta velit veniam quas nam labore possimus excepturi obcaecati et perspiciatis laboriosam voluptates laudantium, pariatur, expedita nobis. At, pariatur?
        Numquam officiis, perferendis temporibus voluptatum totam enim porro dignissimos dolore? Minus explicabo earum amet consequuntur id voluptatibus quisquam quaerat a beatae, cumque harum illum debitis neque rem rerum nisi aliquid.
        Vitae itaque dolores, reiciendis ut quos porro modi. Illum voluptas voluptates accusamus nam neque earum doloribus, possimus officiis excepturi id! Neque necessitatibus sunt illo molestiae at reprehenderit distinctio quasi unde?
        Repellendus, quidem non! Omnis corporis, reprehenderit dicta, dolorem quam nulla deserunt tenetur, nisi voluptatum aperiam vero numquam ipsam! Veniam assumenda eligendi iure tempore, quis veritatis dolorum optio corrupti maiores provident?
        Sunt hic quis porro iure voluptatem molestias quod velit tenetur, voluptates unde veniam officia alias accusantium inventore asperiores commodi sed ex dolores vel corporis maiores numquam! Totam cum beatae quo.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero dolore reprehenderit velit beatae minima consequuntur laborum ratione quos vel. Autem deleniti animi accusamus maiores iure amet obcaecati voluptas beatae impedit?`
    },
    {
        id:'4',
        snippet: "Healh",
        title: "Low your Blood Suger with these Healthy Vegetables",
        img: "https://images.unsplash.com/photo-1514986888952-8cd320577b68?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8a2l0Y2hlbiUyMGZvb2R8ZW58MHx8MHx8&w=1000&q=80",
        content: ` Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero dolore reprehenderit velit beatae minima consequuntur laborum ratione quos vel. Autem deleniti animi accusamus maiores iure amet obcaecati voluptas beatae impedit?
        Animi numquam, illum minus quis beatae eveniet facere reiciendis ipsum natus vero recusandae temporibus nisi consequuntur error facilis et necessitatibus similique dolorem accusamus dolorum officia veritatis! Dignissimos cum nesciunt aperiam!
        Cum, repellendus aut, accusantium veniam iste eligendi quod est voluptate atque voluptatem culpa et adipisci ullam eos fugit nobis officiis voluptates! Ut voluptates architecto nulla maiores voluptatibus rerum explicabo! Ex?
        Ipsum culpa ullam unde laborum voluptatum harum hic natus consectetur aut vel tempore repudiandae doloremque, necessitatibus numquam facilis animi, nulla, consequuntur explicabo. Dicta error repellendus nostrum magni molestias possimus dignissimos?
        Non, quod esse. Alias necessitatibus obcaecati suscipit cum cupiditate praesentium rem, accusamus asperiores amet quam modi molestias reprehenderit recusandae accusantium earum odio animi voluptatibus, nisi itaque totam repellendus delectus molestiae!
        Corporis, minima ab tempore illum voluptates similique mollitia voluptatibus recusandae est nemo ad quo iste doloremque esse a quasi, aperiam consequuntur ut tenetur omnis? Libero, voluptas sed. Sunt, sint eligendi?
        Numquam nulla veritatis deleniti eum sunt aliquam quam non asperiores laboriosam officia impedit ad aperiam inventore reiciendis alias, eveniet voluptatem quis adipisci soluta molestias? Culpa ex distinctio debitis laudantium quo.
        Optio, repellat error. Quod ducimus adipisci, ex molestias soluta sit reprehenderit, consequuntur hic doloremque eveniet, pariatur quisquam dolorum. Officiis illo quia eaque eligendi odio suscipit cumque veniam doloribus id a.
        Minima, beatae corporis nesciunt quos sequi quidem quo! Exercitationem ab, et, eius ullam itaque modi, atque dolor aliquam obcaecati tenetur alias rerum aliquid repudiandae! Sunt voluptatibus quas animi laboriosam mollitia!
        Molestiae earum reiciendis dicta perferendis tempora qui, impedit voluptates eius velit laboriosam rerum architecto itaque, consequuntur eligendi officia? Dolor, dolorem! Commodi asperiores illum a harum quisquam laborum alias sed deserunt.
        Ducimus, hic autem. Repudiandae reiciendis quidem similique numquam modi temporibus dolore nihil fugit minus placeat soluta, cum quaerat. Quam obcaecati nihil aliquam repellendus repudiandae reiciendis quia dolorem quis dolorum error.
        Dolorum blanditiis unde voluptatem corporis pariatur necessitatibus fuga praesentium ducimus ab neque provident consequuntur voluptate vitae exercitationem voluptatum aliquid ullam consectetur laboriosam nesciunt, earum ipsum laudantium at veniam? Provident, laudantium?
        Labore mollitia omnis saepe doloribus excepturi culpa repudiandae aliquam, quos eligendi reiciendis similique, minima a ea incidunt, quod ipsum aspernatur facere debitis. Fugit repellat libero beatae non suscipit officia neque.
        Saepe, sequi ipsam fuga nemo facilis aliquid earum laborum voluptas dolorem laboriosam. Recusandae maxime omnis placeat earum ipsam nostrum architecto debitis minus unde, eveniet quae, est illo eligendi quod dolore.
        Cupiditate minus tempora, dolor ea nisi iste veniam odio obcaecati adipisci ut quas reprehenderit qui nemo repellat beatae praesentium! Architecto harum eum, voluptates perspiciatis dignissimos laborum a beatae optio reiciendis.
        Fugit id molestiae incidunt voluptatibus quaerat cum non dolorum necessitatibus magni soluta velit veniam quas nam labore possimus excepturi obcaecati et perspiciatis laboriosam voluptates laudantium, pariatur, expedita nobis. At, pariatur?
        Numquam officiis, perferendis temporibus voluptatum totam enim porro dignissimos dolore? Minus explicabo earum amet consequuntur id voluptatibus quisquam quaerat a beatae, cumque harum illum debitis neque rem rerum nisi aliquid.
        Vitae itaque dolores, reiciendis ut quos porro modi. Illum voluptas voluptates accusamus nam neque earum doloribus, possimus officiis excepturi id! Neque necessitatibus sunt illo molestiae at reprehenderit distinctio quasi unde?
        Repellendus, quidem non! Omnis corporis, reprehenderit dicta, dolorem quam nulla deserunt tenetur, nisi voluptatum aperiam vero numquam ipsam! Veniam assumenda eligendi iure tempore, quis veritatis dolorum optio corrupti maiores provident?
        Sunt hic quis porro iure voluptatem molestias quod velit tenetur, voluptates unde veniam officia alias accusantium inventore asperiores commodi sed ex dolores vel corporis maiores numquam! Totam cum beatae quo.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero dolore reprehenderit velit beatae minima consequuntur laborum ratione quos vel. Autem deleniti animi accusamus maiores iure amet obcaecati voluptas beatae impedit?`
    },
    {
        id:'5',
        snippet: "Healh",
        title: "Low your Blood Suger with these Healthy Vegetables",
        img: "https://images.unsplash.com/photo-1514986888952-8cd320577b68?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8a2l0Y2hlbiUyMGZvb2R8ZW58MHx8MHx8&w=1000&q=80",
        content: ` Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero dolore reprehenderit velit beatae minima consequuntur laborum ratione quos vel. Autem deleniti animi accusamus maiores iure amet obcaecati voluptas beatae impedit?
        Animi numquam, illum minus quis beatae eveniet facere reiciendis ipsum natus vero recusandae temporibus nisi consequuntur error facilis et necessitatibus similique dolorem accusamus dolorum officia veritatis! Dignissimos cum nesciunt aperiam!
        Cum, repellendus aut, accusantium veniam iste eligendi quod est voluptate atque voluptatem culpa et adipisci ullam eos fugit nobis officiis voluptates! Ut voluptates architecto nulla maiores voluptatibus rerum explicabo! Ex?
        Ipsum culpa ullam unde laborum voluptatum harum hic natus consectetur aut vel tempore repudiandae doloremque, necessitatibus numquam facilis animi, nulla, consequuntur explicabo. Dicta error repellendus nostrum magni molestias possimus dignissimos?
        Non, quod esse. Alias necessitatibus obcaecati suscipit cum cupiditate praesentium rem, accusamus asperiores amet quam modi molestias reprehenderit recusandae accusantium earum odio animi voluptatibus, nisi itaque totam repellendus delectus molestiae!
        Corporis, minima ab tempore illum voluptates similique mollitia voluptatibus recusandae est nemo ad quo iste doloremque esse a quasi, aperiam consequuntur ut tenetur omnis? Libero, voluptas sed. Sunt, sint eligendi?
        Numquam nulla veritatis deleniti eum sunt aliquam quam non asperiores laboriosam officia impedit ad aperiam inventore reiciendis alias, eveniet voluptatem quis adipisci soluta molestias? Culpa ex distinctio debitis laudantium quo.
        Optio, repellat error. Quod ducimus adipisci, ex molestias soluta sit reprehenderit, consequuntur hic doloremque eveniet, pariatur quisquam dolorum. Officiis illo quia eaque eligendi odio suscipit cumque veniam doloribus id a.
        Minima, beatae corporis nesciunt quos sequi quidem quo! Exercitationem ab, et, eius ullam itaque modi, atque dolor aliquam obcaecati tenetur alias rerum aliquid repudiandae! Sunt voluptatibus quas animi laboriosam mollitia!
        Molestiae earum reiciendis dicta perferendis tempora qui, impedit voluptates eius velit laboriosam rerum architecto itaque, consequuntur eligendi officia? Dolor, dolorem! Commodi asperiores illum a harum quisquam laborum alias sed deserunt.
        Ducimus, hic autem. Repudiandae reiciendis quidem similique numquam modi temporibus dolore nihil fugit minus placeat soluta, cum quaerat. Quam obcaecati nihil aliquam repellendus repudiandae reiciendis quia dolorem quis dolorum error.
        Dolorum blanditiis unde voluptatem corporis pariatur necessitatibus fuga praesentium ducimus ab neque provident consequuntur voluptate vitae exercitationem voluptatum aliquid ullam consectetur laboriosam nesciunt, earum ipsum laudantium at veniam? Provident, laudantium?
        Labore mollitia omnis saepe doloribus excepturi culpa repudiandae aliquam, quos eligendi reiciendis similique, minima a ea incidunt, quod ipsum aspernatur facere debitis. Fugit repellat libero beatae non suscipit officia neque.
        Saepe, sequi ipsam fuga nemo facilis aliquid earum laborum voluptas dolorem laboriosam. Recusandae maxime omnis placeat earum ipsam nostrum architecto debitis minus unde, eveniet quae, est illo eligendi quod dolore.
        Cupiditate minus tempora, dolor ea nisi iste veniam odio obcaecati adipisci ut quas reprehenderit qui nemo repellat beatae praesentium! Architecto harum eum, voluptates perspiciatis dignissimos laborum a beatae optio reiciendis.
        Fugit id molestiae incidunt voluptatibus quaerat cum non dolorum necessitatibus magni soluta velit veniam quas nam labore possimus excepturi obcaecati et perspiciatis laboriosam voluptates laudantium, pariatur, expedita nobis. At, pariatur?
        Numquam officiis, perferendis temporibus voluptatum totam enim porro dignissimos dolore? Minus explicabo earum amet consequuntur id voluptatibus quisquam quaerat a beatae, cumque harum illum debitis neque rem rerum nisi aliquid.
        Vitae itaque dolores, reiciendis ut quos porro modi. Illum voluptas voluptates accusamus nam neque earum doloribus, possimus officiis excepturi id! Neque necessitatibus sunt illo molestiae at reprehenderit distinctio quasi unde?
        Repellendus, quidem non! Omnis corporis, reprehenderit dicta, dolorem quam nulla deserunt tenetur, nisi voluptatum aperiam vero numquam ipsam! Veniam assumenda eligendi iure tempore, quis veritatis dolorum optio corrupti maiores provident?
        Sunt hic quis porro iure voluptatem molestias quod velit tenetur, voluptates unde veniam officia alias accusantium inventore asperiores commodi sed ex dolores vel corporis maiores numquam! Totam cum beatae quo.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero dolore reprehenderit velit beatae minima consequuntur laborum ratione quos vel. Autem deleniti animi accusamus maiores iure amet obcaecati voluptas beatae impedit?
  `
    },
    {
        id:'6',
        snippet: "Healh",
        title: "Low your Blood Suger with these Healthy Vegetables",
        img: "https://images.unsplash.com/photo-1514986888952-8cd320577b68?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8a2l0Y2hlbiUyMGZvb2R8ZW58MHx8MHx8&w=1000&q=80",
        content: ` Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero dolore reprehenderit velit beatae minima consequuntur laborum ratione quos vel. Autem deleniti animi accusamus maiores iure amet obcaecati voluptas beatae impedit?
        Animi numquam, illum minus quis beatae eveniet facere reiciendis ipsum natus vero recusandae temporibus nisi consequuntur error facilis et necessitatibus similique dolorem accusamus dolorum officia veritatis! Dignissimos cum nesciunt aperiam!
        Cum, repellendus aut, accusantium veniam iste eligendi quod est voluptate atque voluptatem culpa et adipisci ullam eos fugit nobis officiis voluptates! Ut voluptates architecto nulla maiores voluptatibus rerum explicabo! Ex?
        Ipsum culpa ullam unde laborum voluptatum harum hic natus consectetur aut vel tempore repudiandae doloremque, necessitatibus numquam facilis animi, nulla, consequuntur explicabo. Dicta error repellendus nostrum magni molestias possimus dignissimos?
        Non, quod esse. Alias necessitatibus obcaecati suscipit cum cupiditate praesentium rem, accusamus asperiores amet quam modi molestias reprehenderit recusandae accusantium earum odio animi voluptatibus, nisi itaque totam repellendus delectus molestiae!
        Corporis, minima ab tempore illum voluptates similique mollitia voluptatibus recusandae est nemo ad quo iste doloremque esse a quasi, aperiam consequuntur ut tenetur omnis? Libero, voluptas sed. Sunt, sint eligendi?
        Numquam nulla veritatis deleniti eum sunt aliquam quam non asperiores laboriosam officia impedit ad aperiam inventore reiciendis alias, eveniet voluptatem quis adipisci soluta molestias? Culpa ex distinctio debitis laudantium quo.
        Optio, repellat error. Quod ducimus adipisci, ex molestias soluta sit reprehenderit, consequuntur hic doloremque eveniet, pariatur quisquam dolorum. Officiis illo quia eaque eligendi odio suscipit cumque veniam doloribus id a.
        Minima, beatae corporis nesciunt quos sequi quidem quo! Exercitationem ab, et, eius ullam itaque modi, atque dolor aliquam obcaecati tenetur alias rerum aliquid repudiandae! Sunt voluptatibus quas animi laboriosam mollitia!
        Molestiae earum reiciendis dicta perferendis tempora qui, impedit voluptates eius velit laboriosam rerum architecto itaque, consequuntur eligendi officia? Dolor, dolorem! Commodi asperiores illum a harum quisquam laborum alias sed deserunt.
        Ducimus, hic autem. Repudiandae reiciendis quidem similique numquam modi temporibus dolore nihil fugit minus placeat soluta, cum quaerat. Quam obcaecati nihil aliquam repellendus repudiandae reiciendis quia dolorem quis dolorum error.
        Dolorum blanditiis unde voluptatem corporis pariatur necessitatibus fuga praesentium ducimus ab neque provident consequuntur voluptate vitae exercitationem voluptatum aliquid ullam consectetur laboriosam nesciunt, earum ipsum laudantium at veniam? Provident, laudantium?
        Labore mollitia omnis saepe doloribus excepturi culpa repudiandae aliquam, quos eligendi reiciendis similique, minima a ea incidunt, quod ipsum aspernatur facere debitis. Fugit repellat libero beatae non suscipit officia neque.
        Saepe, sequi ipsam fuga nemo facilis aliquid earum laborum voluptas dolorem laboriosam. Recusandae maxime omnis placeat earum ipsam nostrum architecto debitis minus unde, eveniet quae, est illo eligendi quod dolore.
        Cupiditate minus tempora, dolor ea nisi iste veniam odio obcaecati adipisci ut quas reprehenderit qui nemo repellat beatae praesentium! Architecto harum eum, voluptates perspiciatis dignissimos laborum a beatae optio reiciendis.
        Fugit id molestiae incidunt voluptatibus quaerat cum non dolorum necessitatibus magni soluta velit veniam quas nam labore possimus excepturi obcaecati et perspiciatis laboriosam voluptates laudantium, pariatur, expedita nobis. At, pariatur?
        Numquam officiis, perferendis temporibus voluptatum totam enim porro dignissimos dolore? Minus explicabo earum amet consequuntur id voluptatibus quisquam quaerat a beatae, cumque harum illum debitis neque rem rerum nisi aliquid.
        Vitae itaque dolores, reiciendis ut quos porro modi. Illum voluptas voluptates accusamus nam neque earum doloribus, possimus officiis excepturi id! Neque necessitatibus sunt illo molestiae at reprehenderit distinctio quasi unde?
        Repellendus, quidem non! Omnis corporis, reprehenderit dicta, dolorem quam nulla deserunt tenetur, nisi voluptatum aperiam vero numquam ipsam! Veniam assumenda eligendi iure tempore, quis veritatis dolorum optio corrupti maiores provident?
        Sunt hic quis porro iure voluptatem molestias quod velit tenetur, voluptates unde veniam officia alias accusantium inventore asperiores commodi sed ex dolores vel corporis maiores numquam! Totam cum beatae quo.  Lorem ipsum dolor, sit amet consectetur adipisicing elit. Libero dolore reprehenderit velit beatae minima consequuntur laborum ratione quos vel. Autem deleniti animi accusamus maiores iure amet obcaecati voluptas beatae impedit?`
    },
    

]